---
- name: Install containerd.io
  ansible.builtin.apt:
    name: containerd.io
    state: present
    update_cache: true

- name: Generate containerd config
  ansible.builtin.shell: |
    containerd config default | tee /etc/containerd/config.toml >/dev/null 2>&1
    sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml
  args:
    executable: /bin/bash

- name: Restart and enable containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    enabled: true
