---
- name: Add Docker apt key and repository
  ansible.builtin.shell: |
    set -o pipefail
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/trusted.gpg.d/docker.gpg
    add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  args:
    executable: /bin/bash
    creates: /etc/apt/trusted.gpg.d/docker.gpg
