---
- name: Set hostname
  ansible.builtin.hostname:
    name: k8s-node-1

- name: Initialize Kubernetes cluster
  ansible.builtin.command: kubeadm init
  args:
    creates: /etc/kubernetes/admin.conf
  register: kubeadm_init

- name: Create kube config dir for root
  ansible.builtin.file:
    path: /root/.kube
    state: directory
    mode: '0755'

- name: Copy admin config
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: true
    mode: '0600'
