---
- name: Include base package tasks
  ansible.builtin.include_tasks: packages.yml

- name: Include Docker repository tasks
  ansible.builtin.include_tasks: docker_repo.yml

- name: Include containerd tasks
  ansible.builtin.include_tasks: containerd.yml

- name: Include Kubernetes repository tasks
  ansible.builtin.include_tasks: k8s_repo.yml

- name: Include kubeadm init tasks
  ansible.builtin.include_tasks: kubeadm_init.yml

- name: Include Calico tasks
  ansible.builtin.include_tasks: calico.yml

- name: Include Helm tasks
  ansible.builtin.include_tasks: helm.yml
