---
- name: restart cloudflared
  ansible.builtin.systemd:
    name: cloudflared
    state: restarted
    enabled: true

- name: reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
